//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_SchoolManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class generalnotice
    {
        public int noticeid { get; set; }
        public string noticesubject { get; set; }
        public string noticedescription { get; set; }
        public System.DateTime postdate { get; set; }
    }
}
