//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_SchoolManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class grade
    {
        public int gradeid { get; set; }
        public string classname { get; set; }
        public string sectionname { get; set; }
        public string subjectname { get; set; }
        public string studentname { get; set; }
        public int quiz1 { get; set; }
        public int quiz2 { get; set; }
        public int assignment1 { get; set; }
        public int halfyearlygrade { get; set; }
        public int quiz3 { get; set; }
        public int quiz4 { get; set; }
        public int assignment2 { get; set; }
        public int finalexamgrade { get; set; }
    }
}
