//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_SchoolManagementSystem.Models.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smsEntities : DbContext
    {
        public smsEntities()
            : base("name=smsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<assignment> assignment { get; set; }
        public virtual DbSet<@class> @class { get; set; }
        public virtual DbSet<coursenotice> coursenotice { get; set; }
        public virtual DbSet<generalnotice> generalnotice { get; set; }
        public virtual DbSet<grade> grade { get; set; }
        public virtual DbSet<homework> homework { get; set; }
        public virtual DbSet<live> live { get; set; }
        public virtual DbSet<routine> routine { get; set; }
        public virtual DbSet<section> section { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<subject> subject { get; set; }
        public virtual DbSet<superadmin> superadmin { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<timeslot> timeslot { get; set; }
        public virtual DbSet<tpe> tpe { get; set; }
        public virtual DbSet<uploadnote> uploadnote { get; set; }
    }
}
