//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_SchoolManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id { get; set; }
        public string studentid { get; set; }
        public string studentname { get; set; }
        public string studentpassword { get; set; }
        public System.DateTime studentdob { get; set; }
        public int studentphone { get; set; }
        public string studentaddress { get; set; }
        public string studentemail { get; set; }
        public string studentbloodgroup { get; set; }
        public int studentfees { get; set; }
        public int classid { get; set; }
        public int sectionid { get; set; }
    }
}
