//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_SchoolManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class superadmin
    {
        public int id { get; set; }
        public string superadminid { get; set; }
        public string superadminname { get; set; }
        public string superadminpassword { get; set; }
    }
}
