//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_SchoolManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeslot
    {
        public int timeslotid { get; set; }
        public string time { get; set; }
        public string day { get; set; }
        public int subjectid { get; set; }
        public int sectionid { get; set; }
        public int routineid { get; set; }
    }
}
