//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_SchoolManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadnote
    {
        public int uploadid { get; set; }
        public string directory { get; set; }
        public string filename { get; set; }
        public System.DateTime datetime { get; set; }
        public int sectionid { get; set; }
        public int subjectid { get; set; }
    }
}
